FROM golang:1.17.0 AS builder
WORKDIR /opt
COPY . .
RUN go mod download
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main .

FROM alpine:3.13
WORKDIR /app
COPY --from=builder /opt/main /app/main
