FROM debian:11-slim
RUN apt update -y \
 && apt install -q -y curl jq qemu-utils python3-minimal python3-dev python3-pip
RUN pip install python-openstackclient
RUN curl -L https://github.com/vmware/govmomi/releases/download/v0.24.0/govc_linux_amd64.gz | gunzip > /usr/local/bin/govc \
 && chmod +x /usr/local/bin/govc

