apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-pv-claim
  labels:
    app: ${APP}
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${STORAGE}