server:
  port: "8080"

vcenter:
  url: ""
  username: ""

openstack:
  authurl: ""
  projectid: ""
  projectname: ""
  userdomainname: ""
  username: ""
  password: ""
  regionname: ""
  interface: ""
  identityapiversion: ""

rabbitmq:
  host: [ "" ]
  port: 
  username: ""
  password: ""

mongodb:
  url: ""
  username: ""
  password: ""
  database: ""
  collection: ""

auth:
  validationurl: ""

vault:
  address: ""
  secret: ""
